name: flutter_application_tes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0 # versi terbaru bisa dicek di pub.dev
  line_awesome_flutter: ^2.0.0
  google_fonts: 4.0.4
  flutter_animate: ^4.1.1
  animated_text_kit: ^4.2.2
  image_downloader: ^0.31.0
  permission_handler: ^10.2.0
  url_launcher: ^6.1.10
  auto_size_text: ^3.0.0
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/profile.jpg
    - assets/img/uchiha.jpg
    - assets/img/profilereal.jpeg
    - assets/img/profil.jpg
    - assets/img/proyekcafe.png
    - assets/img/sawitkita.png
    - assets/img/manajemenaset.png

    - assets/tech/bootstrap.png
    - assets/tech/css3.png
    - assets/tech/flutter.png
    - assets/tech/go.png
    - assets/tech/html5.png
    - assets/tech/javascript.png
    - assets/tech/linux.png
    - assets/tech/mongodb.png
    - assets/tech/mysql.png
    - assets/tech/windows.png
    - assets/tech/python.png
    - assets/tech/python1.png
    - assets/tech/figma.png

    - assets/certificates/thumbnails/Flutter Course.png
    - assets/certificates/thumbnails/MTCNA.png
    - assets/certificates/thumbnails/RCNA Routing & Switching.png
    - assets/certificates/thumbnails/RCNA WLAN.png
    - assets/certificates/thumbnails/Riset Sawit BPDPKS.png
    - assets/certificates/thumbnails/Udemy Laravel.png